### ISSUE TITLE
Handle Exception on config error

### ISSUE THREAD

**Issue by goern** [thoth-station/kebechet#120]
**Describe the bug**
```

2018-07-28 05:58:57,425 [1] ERROR    kebechet.config: An error occurred during run of manager {} <class 'kebechet.managers.version.version.VersionManager'> for thoth-station/storages, skipping
--
  | Traceback (most recent call last):
  | File "/usr/local/lib/python3.6/site-packages/kebechet/config.py", line 168, in run
  | instance.run(**manager_configuration)
  | TypeError: run() got an unexpected keyword argument 'assignees'

```

**Expected behavior**
just log the exception...

**Additional context**
This was code before https://github.com/thoth-station/kebechet/pull/118 seeing a configfile after #118

**Comment by fridex** [comment]
The argument is present in the info manager - https://github.com/thoth-station/kebechet/blob/master/kebechet/managers/version/version.py#L170 Was Kebechet rebuild (this parameter was introduced with #118 so probably running old instance with new configuration?)
